name: small_batch_celebahq_recogition

defaults:
  - data: CelebaHQ_Recognition
  - impl: default
  - server: honest-but-curious
  - user: local_gradient
  - _self_
model: ResNet18

# Server and user:
num_queries: 1
  
# User data:
user:
  num_data_points: 2
