name: single_celebahq_gender_fedavg

defaults:
  - data: CelebaHQ_Gender
  - impl: default
  - server: honest-but-curious
  - user: local_updates
  - _self_
model: ResNet18

# Server and user:
num_queries: 1